name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm ci
    - run: sudo apt-get install xvfb
    - name: Lint
      run: npm run lint
    - name: Test
      run:  npm run jest
    - name: Build
      run: npm run build
